name = "document"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-17"

[build.upload]
dir = "src"
format = "modules"
main = "./document.mjs"

[durable_objects]
bindings = [
  { name = "DOCUMENT", class_name = "Document" }
]

[[migrations]]
tag = "v1"
new_classes = ["Document"]